version: "3.1"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gaston
      MYSQL_DATABASE: MACNews
      MYSQL_USER: gaston
      MYSQL_PASSWORD: gaston
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-files/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
